language: nodejs
sudo: false
cache:
  directories:
  - node_modules
before_script:
- npm run setup
- npm run build
script:
- npm run test-only
after_success:
- npm run typedoc
deploy:
- provider: pages
  skip_cleanup: true
  local_dir: "./docs/"
  github_token: "$GITHUB_TOKEN"
- provider: heroku
  app:
    master: teams-frontend
    development: teams-frontend-dev
  skip_cleanup: true
  api_key:
    secure: GQtmEdBJ4NQyFw/j19yKTtpMuj9LA5ahu0TTZ7j+cCeMRDgdNrM8Ktx/YYVFCafZRYNCKJyySJW51Gr0Z+G6SE10Q5R04iMMhAYpomn4vvXLKaPH/aOvyrk0ZhWORL+mh+BDi1IXGgme6BmsNF31olqMdDdfzDuDloqywgtPPXdikEEXae0fE+XiWmMK8cK8/e8G2YMxtT/pv4FAw9VD13n/L+s/HxBV98NbRMVR7pPQnlpiImcKzPJprS0iR1L4KaKjqJMCUDhQYWz5roak05rTy9yjMPd++TfF+Dj/B1L/392UUM0Vi7KzCjxFfdMY9fQEjU6Ot5a5jm0VzTaXHY4De/fnF8Dp4SkFw72buXoiWD0yZ1c3EIrUwKVc+WaE6hLCHQ/BbwipCicbcyp5AnxZSQhJYMg7XPkb6W+sxK0TzNztYkwxywD04YguGZ2eavjzTRIbu06iIYZJFjHVCVO3hS2zBkqnyek79JnhYPzgDhNAgkDZDj4kreVPoNX+itLjy4ts4qi9JGPDWKpfWjf70bxq0ovEdYMWYirmAYkFKnirIDDHvdFm1M0IFJQDmYi7V6Rlf29BADNxTcssIoXhMZY7a8MqiJ05gt7mWnlVs7FtfldE6ikOQyjkUeA5EvnVmvilDOvDg/kaeoYFRfJAscwiIjAjRHSMU+7bFq4=
